### ISSUE TITLE
demo app does notjhing

### ISSUE THREAD

**Issue by pelikhan** [jwunderl/pxt-heap#2]
Maybe create at least one sprite?

**Comment by jwunderl** [comment]
Created a little demo where it makes asteroids and makes them say their own order in closeness to the origin (0,0) / make it repeat that on any button~

**Comment by pelikhan** [comment]
Have them move random speed and update order on game update

**Comment by jwunderl** [comment]
Oooh with bounce on wall that'll be really cool, one sec

**Comment by jwunderl** [comment]
Okay now it's a to reset with new enemies, up to add an enemy, and down to subtract one (minimum 2), and they bounce around the screen / update continually like you said

**Comment by pelikhan** [comment]
Nice!
